openapi: 3.1.0
info:
  title: itle
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
paths:
  /ping:
    get:
      description: Retourne "pong"
      responses:
        '200':
          description: pong retourné avec succès
          content:
            text/plain:
              schema:
                type: string
                example: pong
