openapi: 3.1.0
info:
  title: Gestion d'utilisateur
  description: Retourne un utilisateur sous forme JSON
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
paths:
  /users:
    get:
      description: Récupère une liste en page d'utilisateurs.
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Liste des utilisateurs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Alice
                    email:
                      type: string
                      example: alice@example.com
